//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.18 at 05:02:20 PM CEST 
//


package com.photel.webserviceClient.BDL244.vo.serviceAddRQ;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Product feature distance data.
 * 
 * <p>Java class for ProductFeatureDistance complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProductFeatureDistance">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.hotelbeds.com/schemas/2005/06/messages}ProductFeature">
 *       &lt;sequence>
 *         &lt;element name="AccessType" type="{http://www.hotelbeds.com/schemas/2005/06/messages}HotelbedsFacilityAccessType" minOccurs="0"/>
 *         &lt;element name="DistanceList" type="{http://www.hotelbeds.com/schemas/2005/06/messages}ProductFeatureDistanceItemList" minOccurs="0"/>
 *         &lt;element name="RequiredTimeList" type="{http://www.hotelbeds.com/schemas/2005/06/messages}ProductFeatureDistanceRequiredTimeList" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProductFeatureDistance", propOrder = {
    "accessType",
    "distanceList",
    "requiredTimeList"
})
public class ProductFeatureDistance
    extends ProductFeature
{

    @XmlElement(name = "AccessType")
    protected HotelbedsFacilityAccessType accessType;
    @XmlElement(name = "DistanceList")
    protected ProductFeatureDistanceItemList distanceList;
    @XmlElement(name = "RequiredTimeList")
    protected ProductFeatureDistanceRequiredTimeList requiredTimeList;

    /**
     * Gets the value of the accessType property.
     * 
     * @return
     *     possible object is
     *     {@link HotelbedsFacilityAccessType }
     *     
     */
    public HotelbedsFacilityAccessType getAccessType() {
        return accessType;
    }

    /**
     * Sets the value of the accessType property.
     * 
     * @param value
     *     allowed object is
     *     {@link HotelbedsFacilityAccessType }
     *     
     */
    public void setAccessType(HotelbedsFacilityAccessType value) {
        this.accessType = value;
    }

    /**
     * Gets the value of the distanceList property.
     * 
     * @return
     *     possible object is
     *     {@link ProductFeatureDistanceItemList }
     *     
     */
    public ProductFeatureDistanceItemList getDistanceList() {
        return distanceList;
    }

    /**
     * Sets the value of the distanceList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductFeatureDistanceItemList }
     *     
     */
    public void setDistanceList(ProductFeatureDistanceItemList value) {
        this.distanceList = value;
    }

    /**
     * Gets the value of the requiredTimeList property.
     * 
     * @return
     *     possible object is
     *     {@link ProductFeatureDistanceRequiredTimeList }
     *     
     */
    public ProductFeatureDistanceRequiredTimeList getRequiredTimeList() {
        return requiredTimeList;
    }

    /**
     * Sets the value of the requiredTimeList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductFeatureDistanceRequiredTimeList }
     *     
     */
    public void setRequiredTimeList(ProductFeatureDistanceRequiredTimeList value) {
        this.requiredTimeList = value;
    }

}
