//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.18 at 05:02:20 PM CEST 
//


package com.photel.webserviceClient.BDL244.vo.serviceAddRQ;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Service hotel room type group list.
 * 
 * <p>Java class for ServiceHotelRoomTypeGroupList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceHotelRoomTypeGroupList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RoomTypeGroup" type="{http://www.hotelbeds.com/schemas/2005/06/messages}ServiceHotelRoomTypeGroup" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceHotelRoomTypeGroupList", propOrder = {
    "roomTypeGroup"
})
public class ServiceHotelRoomTypeGroupList {

    @XmlElement(name = "RoomTypeGroup", required = true)
    protected List<ServiceHotelRoomTypeGroup> roomTypeGroup;

    /**
     * Gets the value of the roomTypeGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the roomTypeGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRoomTypeGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ServiceHotelRoomTypeGroup }
     * 
     * 
     */
    public List<ServiceHotelRoomTypeGroup> getRoomTypeGroup() {
        if (roomTypeGroup == null) {
            roomTypeGroup = new ArrayList<ServiceHotelRoomTypeGroup>();
        }
        return this.roomTypeGroup;
    }

}
