//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.13 at 05:38:07 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.hotelbeds.com/schemas/2005/06/messages", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.photel.webserviceClient.BDL244.vo.purchase;
