//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.01 at 12:19:03 PM CEST 
//


package com.photel.webserviceClient.BDL244.vo.purchaseRQ;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * List of product feature distance required time.
 * 
 * <p>Java class for ProductFeatureDistanceRequiredTimeList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProductFeatureDistanceRequiredTimeList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RequiredTime" type="{http://www.hotelbeds.com/schemas/2005/06/messages}ProductFeatureDistanceRequiredTime" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProductFeatureDistanceRequiredTimeList", propOrder = {
    "requiredTime"
})
public class ProductFeatureDistanceRequiredTimeList {

    @XmlElement(name = "RequiredTime", required = true)
    protected List<ProductFeatureDistanceRequiredTime> requiredTime;

    /**
     * Gets the value of the requiredTime property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the requiredTime property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRequiredTime().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProductFeatureDistanceRequiredTime }
     * 
     * 
     */
    public List<ProductFeatureDistanceRequiredTime> getRequiredTime() {
        if (requiredTime == null) {
            requiredTime = new ArrayList<ProductFeatureDistanceRequiredTime>();
        }
        return this.requiredTime;
    }

}
