//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.01 at 12:19:03 PM CEST 
//


package com.photel.webserviceClient.BDL244.vo.purchaseRQ;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Car feature preference.
 * 
 * <p>Java class for ServiceCarPreference complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceCarPreference">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CarGroup" type="{http://www.hotelbeds.com/schemas/2005/06/messages}ProductCarGroup"/>
 *       &lt;/sequence>
 *       &lt;attribute name="preference" use="required" type="{http://www.hotelbeds.com/schemas/2005/06/messages}PreferLevelType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceCarPreference", propOrder = {
    "carGroup"
})
public class ServiceCarPreference {

    @XmlElement(name = "CarGroup", required = true)
    protected ProductCarGroup carGroup;
    @XmlAttribute(required = true)
    protected PreferLevelType preference;

    /**
     * Gets the value of the carGroup property.
     * 
     * @return
     *     possible object is
     *     {@link ProductCarGroup }
     *     
     */
    public ProductCarGroup getCarGroup() {
        return carGroup;
    }

    /**
     * Sets the value of the carGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductCarGroup }
     *     
     */
    public void setCarGroup(ProductCarGroup value) {
        this.carGroup = value;
    }

    /**
     * Gets the value of the preference property.
     * 
     * @return
     *     possible object is
     *     {@link PreferLevelType }
     *     
     */
    public PreferLevelType getPreference() {
        return preference;
    }

    /**
     * Sets the value of the preference property.
     * 
     * @param value
     *     allowed object is
     *     {@link PreferLevelType }
     *     
     */
    public void setPreference(PreferLevelType value) {
        this.preference = value;
    }

}
