//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.18 at 05:02:20 PM CEST 
//


package com.photel.webserviceClient.BDL244.vo.serviceAddRQ;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Concrete product transfer hotel.
 * 
 * <p>Java class for ProductTransferHotel complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProductTransferHotel">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.hotelbeds.com/schemas/2005/06/messages}Product">
 *       &lt;sequence>
 *         &lt;element name="TransferZone" type="{http://www.hotelbeds.com/schemas/2005/06/messages}ProductZone"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProductTransferHotel", propOrder = {
    "transferZone"
})
public class ProductTransferHotel
    extends Product
{

    @XmlElement(name = "TransferZone", required = true)
    protected ProductZone transferZone;

    /**
     * Gets the value of the transferZone property.
     * 
     * @return
     *     possible object is
     *     {@link ProductZone }
     *     
     */
    public ProductZone getTransferZone() {
        return transferZone;
    }

    /**
     * Sets the value of the transferZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductZone }
     *     
     */
    public void setTransferZone(ProductZone value) {
        this.transferZone = value;
    }

}
