//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.18 at 11:05:34 AM CET 
//


package com.photel.hotelan.client.IrqVillaAvailablePrice;

import java.io.Serializable;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import com.photel.data.hotelan.ddbb.hibernate.pojo.HibernateHotel;
import com.photel.data.hotelan.ddbb.hibernate.pojo.HibernateHotelImage;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="BoardId" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="CathegoryId" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="DestinationId" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="Id" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="Price" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="RoomId" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="TypeId" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="ZoneId" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "Villa")
public class Villa  implements Serializable{

    @XmlAttribute(name = "BoardId", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String boardId;
    @XmlAttribute(name = "CathegoryId", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String cathegoryId;
    @XmlAttribute(name = "DestinationId", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String destinationId;
    @XmlAttribute(name = "Id", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String id;
    @XmlAttribute(name = "Name", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String name;
    @XmlAttribute(name = "Price", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String price;
    @XmlAttribute(name = "RoomId", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String roomId;
    @XmlAttribute(name = "TypeId", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String typeId;
    @XmlAttribute(name = "ZoneId", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String zoneId;
    @XmlAttribute(name = "License", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String license;

    
    protected String board;
    protected String cathegory;
    protected String destination;
    protected String room;
    protected String type;
    protected String zone;
    protected String codHotelguide;
    protected String codCrs;
    protected String codPortVill;
    protected String joomlaDescription;
    protected HibernateHotel ddbbHotel;
    protected String joomlaImage;
    protected Map<String,String> joomlaFacilities;
    protected List<HibernateHotelImage> images;
    protected BigDecimal comision;
 
    
	public String getCodPortVill() {
		return codPortVill;
	}

	public void setCodPortVill(String codPortVill) {
		this.codPortVill = codPortVill;
	}

	public BigDecimal getComision() {
		return comision;
	}

	public void setComision(BigDecimal comision) {
		this.comision = comision;
	}

	public List<HibernateHotelImage> getImages() {
		return images;
	}

	public void setImages(List<HibernateHotelImage> images) {
		this.images = images;
	}

	public Map<String, String> getJoomlaFacilities() {
		return joomlaFacilities;
	}

	public void setJoomlaFacilities(Map<String, String> joomlaFacilities) {
		this.joomlaFacilities = joomlaFacilities;
	}
	public void setJoomlaFacilities(String facilities) {
		Map<String, String> joomlaFacilities=new HashMap<String, String>();
		if (facilities!=null && !facilities.equals("")){
			String[] facs=facilities.split(",");
			for (String faci:facs){
				joomlaFacilities.put(faci, faci);
			}
		}
		this.joomlaFacilities = joomlaFacilities;
	}
	public HibernateHotel getDdbbHotel() {
		return ddbbHotel;
	}

	public void setDdbbHotel(HibernateHotel ddbbHotel) {
		this.ddbbHotel = ddbbHotel;
	}

	public String getJoomlaDescription() {
		return joomlaDescription;
	}
	public String getDescription() {
		String ret=null;
		if(joomlaDescription!=null){
			ret=joomlaDescription;
		}else if(ddbbHotel!=null){
			ret=ddbbHotel.getDetails();
		}
		return ret;
	}
	public String getImage() {
		String ret=null;
		if(joomlaImage!=null){
			ret=joomlaImage;
		}else if(ddbbHotel!=null){
			ret=ddbbHotel.getMainImg();
		}
		return ret;
	}
	public BigDecimal getPriceBigDecimalNoComision(){
		BigDecimal pr=null;
		if (price!=null){
			pr=new BigDecimal(price);
		}
		int ret = pr.multiply(new BigDecimal("100")).intValue();
		pr=new BigDecimal(String.valueOf(ret)).divide(new BigDecimal("100")).setScale(2, BigDecimal.ROUND_HALF_UP);
		return pr;
	}
	public BigDecimal getPriceBigDecimal(){
		BigDecimal pr=null;
		if (price!=null){
			pr=new BigDecimal(price);
			if (comision!=null){
				//precio=PrecioPortVill/(1-(comision/100))
				pr=pr.divide(BigDecimal.ONE.subtract(comision.divide(new BigDecimal("100"), 4, RoundingMode.HALF_UP)), 4, RoundingMode.HALF_UP);
			}
		}
		int ret = pr.multiply(new BigDecimal("100")).intValue();
		pr=new BigDecimal(String.valueOf(ret)).divide(new BigDecimal("100")).setScale(2, BigDecimal.ROUND_HALF_UP);
		return pr;
	}
	public BigDecimal getPricePrepago(){
		BigDecimal prepago=null;
		BigDecimal pr=getPriceBigDecimal();
		if (pr!=null && comision!=null){
			prepago=pr.multiply(comision.divide(new BigDecimal("100"), 4, RoundingMode.HALF_UP));
		}
		int ret = prepago.multiply(new BigDecimal("100")).intValue();
		prepago=new BigDecimal(String.valueOf(ret)).divide(new BigDecimal("100")).setScale(2, BigDecimal.ROUND_HALF_UP);
		return prepago;
	}
	public void setJoomlaDescription(String joomlaDescription) {
		this.joomlaDescription = joomlaDescription;
	}

	public String getJoomlaImage() {
		return joomlaImage;
	}

	public void setJoomlaImage(String joomlaImage) {
		this.joomlaImage = joomlaImage;
	}

	public String getCodHotelguide() {
		return codHotelguide;
	}

	public void setCodHotelguide(String codHotelguide) {
		this.codHotelguide = codHotelguide;
	}

	public String getCodCrs() {
		return codCrs;
	}

	public void setCodCrs(String codCrs) {
		this.codCrs = codCrs;
	}

	public String getBoard() {
		return board;
	}

	public void setBoard(String board) {
		this.board = board;
	}

	public String getCathegory() {
		return cathegory;
	}

	public void setCathegory(String cathegory) {
		this.cathegory = cathegory;
	}

	public String getDestination() {
		return destination;
	}

	public void setDestination(String destination) {
		this.destination = destination;
	}

	public String getRoom() {
		return room;
	}

	public void setRoom(String room) {
		this.room = room;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getZone() {
		return zone;
	}

	public void setZone(String zone) {
		this.zone = zone;
	}

	/**
     * Gets the value of the boardId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBoardId() {
        return boardId;
    }

    /**
     * Sets the value of the boardId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBoardId(String value) {
        this.boardId = value;
    }

    /**
     * Gets the value of the cathegoryId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCathegoryId() {
        return cathegoryId;
    }

    /**
     * Sets the value of the cathegoryId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCathegoryId(String value) {
        this.cathegoryId = value;
    }

    /**
     * Gets the value of the destinationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestinationId() {
        return destinationId;
    }

    /**
     * Sets the value of the destinationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestinationId(String value) {
        this.destinationId = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the price property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrice(String value) {
        this.price = value;
    }

    /**
     * Gets the value of the roomId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoomId() {
        return roomId;
    }

    /**
     * Sets the value of the roomId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoomId(String value) {
        this.roomId = value;
    }

    /**
     * Gets the value of the typeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeId() {
        return typeId;
    }

    /**
     * Sets the value of the typeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeId(String value) {
        this.typeId = value;
    }

    /**
     * Gets the value of the zoneId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZoneId() {
        return zoneId;
    }

    /**
     * Sets the value of the zoneId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZoneId(String value) {
        this.zoneId = value;
    }

	public String getLicense() {
		return license;
	}

	public void setLicense(String license) {
		this.license = license;
	}

}
