//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.18 at 05:02:20 PM CEST 
//


package com.photel.webserviceClient.BDL244.vo.serviceAddRQ;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * List of hotel category groups.
 * 
 * <p>Java class for ProductHotelCategoryGroupList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProductHotelCategoryGroupList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HotelCategoryGroup" type="{http://www.hotelbeds.com/schemas/2005/06/messages}ProductHotelCategoryGroup" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProductHotelCategoryGroupList", propOrder = {
    "hotelCategoryGroup"
})
public class ProductHotelCategoryGroupList {

    @XmlElement(name = "HotelCategoryGroup", required = true)
    protected List<ProductHotelCategoryGroup> hotelCategoryGroup;

    /**
     * Gets the value of the hotelCategoryGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hotelCategoryGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHotelCategoryGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProductHotelCategoryGroup }
     * 
     * 
     */
    public List<ProductHotelCategoryGroup> getHotelCategoryGroup() {
        if (hotelCategoryGroup == null) {
            hotelCategoryGroup = new ArrayList<ProductHotelCategoryGroup>();
        }
        return this.hotelCategoryGroup;
    }

}
