//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.08 at 09:26:37 AM CET 
//


package com.photel.webserviceClient.BDL244.vo.avail;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Contains simple hotel category list for a hotel category group.
 * 
 * <p>Java class for ProductHotelCategoryGroup complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProductHotelCategoryGroup">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GroupHotelCategory" type="{http://www.hotelbeds.com/schemas/2005/06/messages}ProductHotelCategory"/>
 *         &lt;element name="SimpleHotelCategoryList" type="{http://www.hotelbeds.com/schemas/2005/06/messages}ProductHotelCategoryList"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProductHotelCategoryGroup", propOrder = {
    "groupHotelCategory",
    "simpleHotelCategoryList"
})
public class ProductHotelCategoryGroup {

    @XmlElement(name = "GroupHotelCategory", required = true)
    protected ProductHotelCategory groupHotelCategory;
    @XmlElement(name = "SimpleHotelCategoryList", required = true)
    protected ProductHotelCategoryList simpleHotelCategoryList;

    /**
     * Gets the value of the groupHotelCategory property.
     * 
     * @return
     *     possible object is
     *     {@link ProductHotelCategory }
     *     
     */
    public ProductHotelCategory getGroupHotelCategory() {
        return groupHotelCategory;
    }

    /**
     * Sets the value of the groupHotelCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductHotelCategory }
     *     
     */
    public void setGroupHotelCategory(ProductHotelCategory value) {
        this.groupHotelCategory = value;
    }

    /**
     * Gets the value of the simpleHotelCategoryList property.
     * 
     * @return
     *     possible object is
     *     {@link ProductHotelCategoryList }
     *     
     */
    public ProductHotelCategoryList getSimpleHotelCategoryList() {
        return simpleHotelCategoryList;
    }

    /**
     * Sets the value of the simpleHotelCategoryList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductHotelCategoryList }
     *     
     */
    public void setSimpleHotelCategoryList(ProductHotelCategoryList value) {
        this.simpleHotelCategoryList = value;
    }

}
