//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.08 at 09:26:37 AM CET 
//


package com.photel.webserviceClient.BDL244.vo.avail;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Travel information for a transfer service.
 * 
 * <p>Java class for ServiceTransferTravelInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceTransferTravelInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DepartInfo" type="{http://www.hotelbeds.com/schemas/2005/06/messages}ProductTransferTerminal" minOccurs="0"/>
 *         &lt;element name="ArrivalInfo" type="{http://www.hotelbeds.com/schemas/2005/06/messages}ProductTransferTerminal" minOccurs="0"/>
 *         &lt;element name="TravelNumber" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="7"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceTransferTravelInfo", propOrder = {
    "departInfo",
    "arrivalInfo",
    "travelNumber"
})
public class ServiceTransferTravelInfo {

    @XmlElement(name = "DepartInfo")
    protected ProductTransferTerminal departInfo;
    @XmlElement(name = "ArrivalInfo")
    protected ProductTransferTerminal arrivalInfo;
    @XmlElement(name = "TravelNumber")
    protected String travelNumber;

    /**
     * Gets the value of the departInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ProductTransferTerminal }
     *     
     */
    public ProductTransferTerminal getDepartInfo() {
        return departInfo;
    }

    /**
     * Sets the value of the departInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductTransferTerminal }
     *     
     */
    public void setDepartInfo(ProductTransferTerminal value) {
        this.departInfo = value;
    }

    /**
     * Gets the value of the arrivalInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ProductTransferTerminal }
     *     
     */
    public ProductTransferTerminal getArrivalInfo() {
        return arrivalInfo;
    }

    /**
     * Sets the value of the arrivalInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductTransferTerminal }
     *     
     */
    public void setArrivalInfo(ProductTransferTerminal value) {
        this.arrivalInfo = value;
    }

    /**
     * Gets the value of the travelNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTravelNumber() {
        return travelNumber;
    }

    /**
     * Sets the value of the travelNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTravelNumber(String value) {
        this.travelNumber = value;
    }

}
