//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.18 at 05:02:20 PM CEST 
//


package com.photel.webserviceClient.BDL244.vo.serviceAddRQ;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * List of hotel rooms.
 * 
 * <p>Java class for ServiceHotelRoomList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceHotelRoomList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HotelOccupancy" type="{http://www.hotelbeds.com/schemas/2005/06/messages}ServiceHotelOccupancy" minOccurs="0"/>
 *         &lt;element name="HotelRoom" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.hotelbeds.com/schemas/2005/06/messages}ServiceHotelRoom">
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceHotelRoomList", propOrder = {
    "hotelOccupancy",
    "hotelRoom"
})
public class ServiceHotelRoomList {

    @XmlElement(name = "HotelOccupancy")
    protected ServiceHotelOccupancy hotelOccupancy;
    @XmlElement(name = "HotelRoom", required = true)
    protected List<ServiceHotelRoomList.HotelRoom> hotelRoom;

    /**
     * Gets the value of the hotelOccupancy property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceHotelOccupancy }
     *     
     */
    public ServiceHotelOccupancy getHotelOccupancy() {
        return hotelOccupancy;
    }

    /**
     * Sets the value of the hotelOccupancy property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceHotelOccupancy }
     *     
     */
    public void setHotelOccupancy(ServiceHotelOccupancy value) {
        this.hotelOccupancy = value;
    }

    /**
     * Gets the value of the hotelRoom property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hotelRoom property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHotelRoom().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ServiceHotelRoomList.HotelRoom }
     * 
     * 
     */
    public List<ServiceHotelRoomList.HotelRoom> getHotelRoom() {
        if (hotelRoom == null) {
            hotelRoom = new ArrayList<ServiceHotelRoomList.HotelRoom>();
        }
        return this.hotelRoom;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.hotelbeds.com/schemas/2005/06/messages}ServiceHotelRoom">
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class HotelRoom
        extends ServiceHotelRoom
    {


    }

}
