//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.08 at 09:25:53 AM CET 
//


package com.photel.webserviceClient.BDL244.vo.avail;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.hotelbeds.com/schemas/2005/06/messages}CoreResponse">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="PaginationData" type="{http://www.hotelbeds.com/schemas/2005/06/messages}PaginationResponseData"/>
 *         &lt;element name="ServiceHotel" type="{http://www.hotelbeds.com/schemas/2005/06/messages}ServiceHotel" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="timeToExpiration" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="totalItems" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "paginationData",
    "serviceHotel"
})
@XmlRootElement(name = "HotelValuedAvailRS")
public class HotelValuedAvailRS
    extends CoreResponse
{

    @XmlElement(name = "PaginationData")
    protected PaginationResponseData paginationData;
    @XmlElement(name = "ServiceHotel")
    protected List<ServiceHotel> serviceHotel;
    @XmlAttribute
    protected Long timeToExpiration;
    @XmlAttribute
    protected Integer totalItems;

    /**
     * Gets the value of the paginationData property.
     * 
     * @return
     *     possible object is
     *     {@link PaginationResponseData }
     *     
     */
    public PaginationResponseData getPaginationData() {
        return paginationData;
    }

    /**
     * Sets the value of the paginationData property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaginationResponseData }
     *     
     */
    public void setPaginationData(PaginationResponseData value) {
        this.paginationData = value;
    }

    /**
     * Gets the value of the serviceHotel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the serviceHotel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getServiceHotel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ServiceHotel }
     * 
     * 
     */
    public List<ServiceHotel> getServiceHotel() {
        if (serviceHotel == null) {
            serviceHotel = new ArrayList<ServiceHotel>();
        }
        return this.serviceHotel;
    }

    /**
     * Gets the value of the timeToExpiration property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTimeToExpiration() {
        return timeToExpiration;
    }

    /**
     * Sets the value of the timeToExpiration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTimeToExpiration(Long value) {
        this.timeToExpiration = value;
    }

    /**
     * Gets the value of the totalItems property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTotalItems() {
        return totalItems;
    }

    /**
     * Sets the value of the totalItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTotalItems(Integer value) {
        this.totalItems = value;
    }

}
