//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.08 at 09:26:37 AM CET 
//


package com.photel.webserviceClient.BDL244.vo.avail;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Audit data returned in all responses.
 * 
 * <p>Java class for AuditData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AuditData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProcessTime" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="Timestamp">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="23"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RequestHost">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="200"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ServerName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ServerId">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SchemaRelease">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="HydraCoreRelease">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="HydraEnumerationsRelease">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MerlinRelease">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AuditData", propOrder = {
    "processTime",
    "timestamp",
    "requestHost",
    "serverName",
    "serverId",
    "schemaRelease",
    "hydraCoreRelease",
    "hydraEnumerationsRelease",
    "merlinRelease"
})
public class AuditData {

    @XmlElement(name = "ProcessTime")
    protected long processTime;
    @XmlElement(name = "Timestamp", required = true)
    protected String timestamp;
    @XmlElement(name = "RequestHost", required = true)
    protected String requestHost;
    @XmlElement(name = "ServerName", required = true)
    protected String serverName;
    @XmlElement(name = "ServerId", required = true)
    protected String serverId;
    @XmlElement(name = "SchemaRelease", required = true)
    protected String schemaRelease;
    @XmlElement(name = "HydraCoreRelease", required = true)
    protected String hydraCoreRelease;
    @XmlElement(name = "HydraEnumerationsRelease", required = true)
    protected String hydraEnumerationsRelease;
    @XmlElement(name = "MerlinRelease", required = true)
    protected String merlinRelease;

    /**
     * Gets the value of the processTime property.
     * 
     */
    public long getProcessTime() {
        return processTime;
    }

    /**
     * Sets the value of the processTime property.
     * 
     */
    public void setProcessTime(long value) {
        this.processTime = value;
    }

    /**
     * Gets the value of the timestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimestamp(String value) {
        this.timestamp = value;
    }

    /**
     * Gets the value of the requestHost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestHost() {
        return requestHost;
    }

    /**
     * Sets the value of the requestHost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestHost(String value) {
        this.requestHost = value;
    }

    /**
     * Gets the value of the serverName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServerName() {
        return serverName;
    }

    /**
     * Sets the value of the serverName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServerName(String value) {
        this.serverName = value;
    }

    /**
     * Gets the value of the serverId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServerId() {
        return serverId;
    }

    /**
     * Sets the value of the serverId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServerId(String value) {
        this.serverId = value;
    }

    /**
     * Gets the value of the schemaRelease property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemaRelease() {
        return schemaRelease;
    }

    /**
     * Sets the value of the schemaRelease property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemaRelease(String value) {
        this.schemaRelease = value;
    }

    /**
     * Gets the value of the hydraCoreRelease property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHydraCoreRelease() {
        return hydraCoreRelease;
    }

    /**
     * Sets the value of the hydraCoreRelease property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHydraCoreRelease(String value) {
        this.hydraCoreRelease = value;
    }

    /**
     * Gets the value of the hydraEnumerationsRelease property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHydraEnumerationsRelease() {
        return hydraEnumerationsRelease;
    }

    /**
     * Sets the value of the hydraEnumerationsRelease property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHydraEnumerationsRelease(String value) {
        this.hydraEnumerationsRelease = value;
    }

    /**
     * Gets the value of the merlinRelease property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerlinRelease() {
        return merlinRelease;
    }

    /**
     * Sets the value of the merlinRelease property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerlinRelease(String value) {
        this.merlinRelease = value;
    }

}
