//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.07 at 09:47:00 AM CET 
//


package com.photel.webserviceClient.BDL244.vo.avail;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.photel.webserviceClient.BDL244.vo.avail package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create an instance of {@link HotelValuedAvailRS }
     * 
     */
    public HotelValuedAvailRS createHotelValuedAvailRS() {
        return new HotelValuedAvailRS();
    }

 

    //*******************************************//
    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.photel.webserviceClient.BDL244.vo.avail
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Contract }
     * 
     */
    public Contract createContract() {
        return new Contract();
    }

    /**
     * Create an instance of {@link ServiceTicketModalityType }
     * 
     */
    public ServiceTicketModalityType createServiceTicketModalityType() {
        return new ServiceTicketModalityType();
    }

    /**
     * Create an instance of {@link ExtendedDataList }
     * 
     */
    public ExtendedDataList createExtendedDataList() {
        return new ExtendedDataList();
    }

    /**
     * Create an instance of {@link ServiceTransferAvailData }
     * 
     */
    public ServiceTransferAvailData createServiceTransferAvailData() {
        return new ServiceTransferAvailData();
    }

    /**
     * Create an instance of {@link ZoneGroup }
     * 
     */
    public ZoneGroup createZoneGroup() {
        return new ZoneGroup();
    }

    /**
     * Create an instance of {@link DateTime }
     * 
     */
    public DateTime createDateTime() {
        return new DateTime();
    }

    /**
     * Create an instance of {@link ProductTicket }
     * 
     */
    public ProductTicket createProductTicket() {
        return new ProductTicket();
    }

    /**
     * Create an instance of {@link ServiceHotelOccupancy }
     * 
     */
    public ServiceHotelOccupancy createServiceHotelOccupancy() {
        return new ServiceHotelOccupancy();
    }

    /**
     * Create an instance of {@link ServiceTransferTravelInfo }
     * 
     */
    public ServiceTransferTravelInfo createServiceTransferTravelInfo() {
        return new ServiceTransferTravelInfo();
    }

    /**
     * Create an instance of {@link OperationDate }
     * 
     */
    public OperationDate createOperationDate() {
        return new OperationDate();
    }

    /**
     * Create an instance of {@link ConfirmationServiceDataCar }
     * 
     */
    public ConfirmationServiceDataCar createConfirmationServiceDataCar() {
        return new ConfirmationServiceDataCar();
    }

    /**
     * Create an instance of {@link PaymentData }
     * 
     */
    public PaymentData createPaymentData() {
        return new PaymentData();
    }

    /**
     * Create an instance of {@link ZoneGroupList }
     * 
     */
    public ZoneGroupList createZoneGroupList() {
        return new ZoneGroupList();
    }

    /**
     * Create an instance of {@link ServicePriceList }
     * 
     */
    public ServicePriceList createServicePriceList() {
        return new ServicePriceList();
    }

    /**
     * Create an instance of {@link ServiceSupplier }
     * 
     */
    public ServiceSupplier createServiceSupplier() {
        return new ServiceSupplier();
    }

    /**
     * Create an instance of {@link ProductCodeList }
     * 
     */
    public ProductCodeList createProductCodeList() {
        return new ProductCodeList();
    }

    /**
     * Create an instance of {@link ServiceCarSpecialEquip }
     * 
     */
    public ServiceCarSpecialEquip createServiceCarSpecialEquip() {
        return new ServiceCarSpecialEquip();
    }

    /**
     * Create an instance of {@link ProductHotelBoardGroupList }
     * 
     */
    public ProductHotelBoardGroupList createProductHotelBoardGroupList() {
        return new ProductHotelBoardGroupList();
    }

    /**
     * Create an instance of {@link PaymentCommissionableData }
     * 
     */
    public PaymentCommissionableData createPaymentCommissionableData() {
        return new PaymentCommissionableData();
    }

    /**
     * Create an instance of {@link ServiceHotelRoomType }
     * 
     */
    public ServiceHotelRoomType createServiceHotelRoomType() {
        return new ServiceHotelRoomType();
    }

    /**
     * Create an instance of {@link CancellationProtection }
     * 
     */
    public CancellationProtection createCancellationProtection() {
        return new CancellationProtection();
    }

    /**
     * Create an instance of {@link ProductImageList }
     * 
     */
    public ProductImageList createProductImageList() {
        return new ProductImageList();
    }

    /**
     * Create an instance of {@link ProductWebList }
     * 
     */
    public ProductWebList createProductWebList() {
        return new ProductWebList();
    }

    /**
     * Create an instance of {@link ContactInfo }
     * 
     */
    public ContactInfo createContactInfo() {
        return new ContactInfo();
    }

    /**
     * Create an instance of {@link Reference }
     * 
     */
    public Reference createReference() {
        return new Reference();
    }

    /**
     * Create an instance of {@link PriceList }
     * 
     */
    public PriceList createPriceList() {
        return new PriceList();
    }

    /**
     * Create an instance of {@link PaginationRequestData }
     * 
     */
    public PaginationRequestData createPaginationRequestData() {
        return new PaginationRequestData();
    }

    /**
     * Create an instance of {@link ServiceList }
     * 
     */
    public ServiceList createServiceList() {
        return new ServiceList();
    }

    /**
     * Create an instance of {@link ProductFeatureGroup }
     * 
     */
    public ProductFeatureGroup createProductFeatureGroup() {
        return new ProductFeatureGroup();
    }

    /**
     * Create an instance of {@link ProductHotelIssue }
     * 
     */
    public ProductHotelIssue createProductHotelIssue() {
        return new ProductHotelIssue();
    }

    /**
     * Create an instance of {@link AgencyIdentification }
     * 
     */
    public AgencyIdentification createAgencyIdentification() {
        return new AgencyIdentification();
    }

    /**
     * Create an instance of {@link PaymentCard }
     * 
     */
    public PaymentCard createPaymentCard() {
        return new PaymentCard();
    }

    /**
     * Create an instance of {@link ProductEmail }
     * 
     */
    public ProductEmail createProductEmail() {
        return new ProductEmail();
    }

    /**
     * Create an instance of {@link ExtraOverride }
     * 
     */
    public ExtraOverride createExtraOverride() {
        return new ExtraOverride();
    }

    /**
     * Create an instance of {@link ProductVendorList }
     * 
     */
    public ProductVendorList createProductVendorList() {
        return new ProductVendorList();
    }

    /**
     * Create an instance of {@link IncomingOffice }
     * 
     */
    public IncomingOffice createIncomingOffice() {
        return new IncomingOffice();
    }

    /**
     * Create an instance of {@link ConfirmationServiceDataTicket }
     * 
     */
    public ConfirmationServiceDataTicket createConfirmationServiceDataTicket() {
        return new ConfirmationServiceDataTicket();
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link ServiceHotelRoomList }
     * 
     */
    public ServiceHotelRoomList createServiceHotelRoomList() {
        return new ServiceHotelRoomList();
    }

    /**
     * Create an instance of {@link ServiceOccupancy }
     * 
     */
    public ServiceOccupancy createServiceOccupancy() {
        return new ServiceOccupancy();
    }

    /**
     * Create an instance of {@link ProductFeatureService }
     * 
     */
    public ProductFeatureService createProductFeatureService() {
        return new ProductFeatureService();
    }

    /**
     * Create an instance of {@link Destination }
     * 
     */
    public Destination createDestination() {
        return new Destination();
    }

    /**
     * Create an instance of {@link ConfirmationServiceDataHotel }
     * 
     */
    public ConfirmationServiceDataHotel createConfirmationServiceDataHotel() {
        return new ConfirmationServiceDataHotel();
    }

    /**
     * Create an instance of {@link Country }
     * 
     */
    public Country createCountry() {
        return new Country();
    }

    /**
     * Create an instance of {@link ProductHotelBoardList }
     * 
     */
    public ProductHotelBoardList createProductHotelBoardList() {
        return new ProductHotelBoardList();
    }

    /**
     * Create an instance of {@link ProductTransferVehicleType }
     * 
     */
    public ProductTransferVehicleType createProductTransferVehicleType() {
        return new ProductTransferVehicleType();
    }

    /**
     * Create an instance of {@link ProductHotel }
     * 
     */
    public ProductHotel createProductHotel() {
        return new ProductHotel();
    }

    /**
     * Create an instance of {@link ContractClassificationList }
     * 
     */
    public ContractClassificationList createContractClassificationList() {
        return new ContractClassificationList();
    }

    /**
     * Create an instance of {@link ProductFeatureData }
     * 
     */
    public ProductFeatureData createProductFeatureData() {
        return new ProductFeatureData();
    }

    /**
     * Create an instance of {@link ProductContactNumber }
     * 
     */
    public ProductContactNumber createProductContactNumber() {
        return new ProductContactNumber();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link ServiceTicketModalityMode }
     * 
     */
    public ServiceTicketModalityMode createServiceTicketModalityMode() {
        return new ServiceTicketModalityMode();
    }

    /**
     * Create an instance of {@link ServiceHotelRoomTypeGroup }
     * 
     */
    public ServiceHotelRoomTypeGroup createServiceHotelRoomTypeGroup() {
        return new ServiceHotelRoomTypeGroup();
    }

    /**
     * Create an instance of {@link ProductDescriptionList }
     * 
     */
    public ProductDescriptionList createProductDescriptionList() {
        return new ProductDescriptionList();
    }

    /**
     * Create an instance of {@link ProductFeatureList }
     * 
     */
    public ProductFeatureList createProductFeatureList() {
        return new ProductFeatureList();
    }

    /**
     * Create an instance of {@link ServiceModificationPolicyList }
     * 
     */
    public ServiceModificationPolicyList createServiceModificationPolicyList() {
        return new ServiceModificationPolicyList();
    }

    /**
     * Create an instance of {@link ServiceInsuranceModality }
     * 
     */
    public ServiceInsuranceModality createServiceInsuranceModality() {
        return new ServiceInsuranceModality();
    }

    /**
     * Create an instance of {@link ProductTransferType }
     * 
     */
    public ProductTransferType createProductTransferType() {
        return new ProductTransferType();
    }

    /**
     * Create an instance of {@link ServiceHotelRoomTypeList }
     * 
     */
    public ServiceHotelRoomTypeList createServiceHotelRoomTypeList() {
        return new ServiceHotelRoomTypeList();
    }

    /**
     * Create an instance of {@link ServiceTicket }
     * 
     */
    public ServiceTicket createServiceTicket() {
        return new ServiceTicket();
    }

    /**
     * Create an instance of {@link ProductTransferHotel }
     * 
     */
    public ProductTransferHotel createProductTransferHotel() {
        return new ProductTransferHotel();
    }

    /**
     * Create an instance of {@link AdditionalCost }
     * 
     */
    public AdditionalCost createAdditionalCost() {
        return new AdditionalCost();
    }

    /**
     * Create an instance of {@link ConfirmationServiceDataTransfer }
     * 
     */
    public ConfirmationServiceDataTransfer createConfirmationServiceDataTransfer() {
        return new ConfirmationServiceDataTransfer();
    }

    /**
     * Create an instance of {@link ProductCarGroupList }
     * 
     */
    public ProductCarGroupList createProductCarGroupList() {
        return new ProductCarGroupList();
    }

    /**
     * Create an instance of {@link ProductImage }
     * 
     */
    public ProductImage createProductImage() {
        return new ProductImage();
    }

    /**
     * Create an instance of {@link ConfirmationServiceDataList }
     * 
     */
    public ConfirmationServiceDataList createConfirmationServiceDataList() {
        return new ConfirmationServiceDataList();
    }

    /**
     * Create an instance of {@link Card }
     * 
     */
    public Card createCard() {
        return new Card();
    }

    /**
     * Create an instance of {@link Currency }
     * 
     */
    public Currency createCurrency() {
        return new Currency();
    }

    /**
     * Create an instance of {@link ServiceTicketModality.ChildAge }
     * 
     */
    public ServiceTicketModality.ChildAge createServiceTicketModalityChildAge() {
        return new ServiceTicketModality.ChildAge();
    }

    /**
     * Create an instance of {@link ServiceHotelRoomList.HotelRoom }
     * 
     */
    public ServiceHotelRoomList.HotelRoom createServiceHotelRoomListHotelRoom() {
        return new ServiceHotelRoomList.HotelRoom();
    }

    /**
     * Create an instance of {@link Position }
     * 
     */
    public Position createPosition() {
        return new Position();
    }

    /**
     * Create an instance of {@link ProductFeatureSport }
     * 
     */
    public ProductFeatureSport createProductFeatureSport() {
        return new ProductFeatureSport();
    }

    /**
     * Create an instance of {@link ProductEmailList }
     * 
     */
    public ProductEmailList createProductEmailList() {
        return new ProductEmailList();
    }

    /**
     * Create an instance of {@link ProductInsurance }
     * 
     */
    public ProductInsurance createProductInsurance() {
        return new ProductInsurance();
    }

    /**
     * Create an instance of {@link ServiceHotelRoomTypeGroupList }
     * 
     */
    public ServiceHotelRoomTypeGroupList createServiceHotelRoomTypeGroupList() {
        return new ServiceHotelRoomTypeGroupList();
    }

    /**
     * Create an instance of {@link ServiceHotelOccupancyList }
     * 
     */
    public ServiceHotelOccupancyList createServiceHotelOccupancyList() {
        return new ServiceHotelOccupancyList();
    }

    /**
     * Create an instance of {@link com.photel.webserviceClient.BDL244.vo.avail.Service.SellingPrice }
     * 
     */
    public com.photel.webserviceClient.BDL244.vo.avail.Service.SellingPrice createServiceSellingPrice() {
        return new com.photel.webserviceClient.BDL244.vo.avail.Service.SellingPrice();
    }

    /**
     * Create an instance of {@link ProductDescription }
     * 
     */
    public ProductDescription createProductDescription() {
        return new ProductDescription();
    }

    /**
     * Create an instance of {@link ProductHotelCategoryGroup }
     * 
     */
    public ProductHotelCategoryGroup createProductHotelCategoryGroup() {
        return new ProductHotelCategoryGroup();
    }

    /**
     * Create an instance of {@link AuditData }
     * 
     */
    public AuditData createAuditData() {
        return new AuditData();
    }

    /**
     * Create an instance of {@link ProductTransferTerminal }
     * 
     */
    public ProductTransferTerminal createProductTransferTerminal() {
        return new ProductTransferTerminal();
    }

    /**
     * Create an instance of {@link Comment }
     * 
     */
    public Comment createComment() {
        return new Comment();
    }

    /**
     * Create an instance of {@link ProductCarOfficeList }
     * 
     */
    public ProductCarOfficeList createProductCarOfficeList() {
        return new ProductCarOfficeList();
    }

    /**
     * Create an instance of {@link ProductFeatureDistanceItem }
     * 
     */
    public ProductFeatureDistanceItem createProductFeatureDistanceItem() {
        return new ProductFeatureDistanceItem();
    }

    /**
     * Create an instance of {@link ServiceCarPreference }
     * 
     */
    public ServiceCarPreference createServiceCarPreference() {
        return new ServiceCarPreference();
    }

    /**
     * Create an instance of {@link ServiceCar }
     * 
     */
    public ServiceCar createServiceCar() {
        return new ServiceCar();
    }

    /**
     * Create an instance of {@link ProductFeatureDistanceRequiredTimeList }
     * 
     */
    public ProductFeatureDistanceRequiredTimeList createProductFeatureDistanceRequiredTimeList() {
        return new ProductFeatureDistanceRequiredTimeList();
    }

    /**
     * Create an instance of {@link ServiceModificationPolicy }
     * 
     */
    public ServiceModificationPolicy createServiceModificationPolicy() {
        return new ServiceModificationPolicy();
    }

    /**
     * Create an instance of {@link com.photel.webserviceClient.BDL244.vo.avail.SellingPrice }
     * 
     */
    public com.photel.webserviceClient.BDL244.vo.avail.SellingPrice createSellingPrice() {
        return new com.photel.webserviceClient.BDL244.vo.avail.SellingPrice();
    }

    /**
     * Create an instance of {@link ContractList }
     * 
     */
    public ContractList createContractList() {
        return new ContractList();
    }

    /**
     * Create an instance of {@link ProductCarGroup }
     * 
     */
    public ProductCarGroup createProductCarGroup() {
        return new ProductCarGroup();
    }

    /**
     * Create an instance of {@link ProductHotel.ChildAge }
     * 
     */
    public ProductHotel.ChildAge createProductHotelChildAge() {
        return new ProductHotel.ChildAge();
    }

    /**
     * Create an instance of {@link ProductVendor }
     * 
     */
    public ProductVendor createProductVendor() {
        return new ProductVendor();
    }

    /**
     * Create an instance of {@link ProductFeatureDistance }
     * 
     */
    public ProductFeatureDistance createProductFeatureDistance() {
        return new ProductFeatureDistance();
    }

    /**
     * Create an instance of {@link ConfirmationPurchaseData }
     * 
     */
    public ConfirmationPurchaseData createConfirmationPurchaseData() {
        return new ConfirmationPurchaseData();
    }

    /**
     * Create an instance of {@link Credentials }
     * 
     */
    public Credentials createCredentials() {
        return new Credentials();
    }

    /**
     * Create an instance of {@link ProductZone }
     * 
     */
    public ProductZone createProductZone() {
        return new ProductZone();
    }

    /**
     * Create an instance of {@link ProductFeatureDistanceRequiredTime }
     * 
     */
    public ProductFeatureDistanceRequiredTime createProductFeatureDistanceRequiredTime() {
        return new ProductFeatureDistanceRequiredTime();
    }

    /**
     * Create an instance of {@link Zone }
     * 
     */
    public Zone createZone() {
        return new Zone();
    }

    /**
     * Create an instance of {@link ProductHotelCategoryList }
     * 
     */
    public ProductHotelCategoryList createProductHotelCategoryList() {
        return new ProductHotelCategoryList();
    }

    /**
     * Create an instance of {@link HotelbedsErrorList }
     * 
     */
    public HotelbedsErrorList createHotelbedsErrorList() {
        return new HotelbedsErrorList();
    }

    /**
     * Create an instance of {@link Classification }
     * 
     */
    public Classification createClassification() {
        return new Classification();
    }

    /**
     * Create an instance of {@link ServicePrice.SellingPrice }
     * 
     */
    public ServicePrice.SellingPrice createServicePriceSellingPrice() {
        return new ServicePrice.SellingPrice();
    }

    /**
     * Create an instance of {@link CustomerList }
     * 
     */
    public CustomerList createCustomerList() {
        return new CustomerList();
    }

    /**
     * Create an instance of {@link ExtendedData }
     * 
     */
    public ExtendedData createExtendedData() {
        return new ExtendedData();
    }

    /**
     * Create an instance of {@link ProductHotelCategory }
     * 
     */
    public ProductHotelCategory createProductHotelCategory() {
        return new ProductHotelCategory();
    }

    /**
     * Create an instance of {@link ServiceCarSpecialEquipList }
     * 
     */
    public ServiceCarSpecialEquipList createServiceCarSpecialEquipList() {
        return new ServiceCarSpecialEquipList();
    }

    /**
     * Create an instance of {@link PaginationResponseData }
     * 
     */
    public PaginationResponseData createPaginationResponseData() {
        return new PaginationResponseData();
    }

    /**
     * Create an instance of {@link ServiceHotel }
     * 
     */
    public ServiceHotel createServiceHotel() {
        return new ServiceHotel();
    }

    /**
     * Create an instance of {@link CardList }
     * 
     */
    public CardList createCardList() {
        return new CardList();
    }

    /**
     * Create an instance of {@link HotelbedsError }
     * 
     */
    public HotelbedsError createHotelbedsError() {
        return new HotelbedsError();
    }

    /**
     * Create an instance of {@link DestinationGroup }
     * 
     */
    public DestinationGroup createDestinationGroup() {
        return new DestinationGroup();
    }

    /**
     * Create an instance of {@link ProductWeb }
     * 
     */
    public ProductWeb createProductWeb() {
        return new ProductWeb();
    }

    /**
     * Create an instance of {@link AdditionalCostList }
     * 
     */
    public AdditionalCostList createAdditionalCostList() {
        return new AdditionalCostList();
    }

    /**
     * Create an instance of {@link ServiceHotelRoom }
     * 
     */
    public ServiceHotelRoom createServiceHotelRoom() {
        return new ServiceHotelRoom();
    }

    /**
     * Create an instance of {@link CommentList }
     * 
     */
    public CommentList createCommentList() {
        return new CommentList();
    }

    /**
     * Create an instance of {@link ProductHotelBoardGroup }
     * 
     */
    public ProductHotelBoardGroup createProductHotelBoardGroup() {
        return new ProductHotelBoardGroup();
    }

    /**
     * Create an instance of {@link ProductCarOffice }
     * 
     */
    public ProductCarOffice createProductCarOffice() {
        return new ProductCarOffice();
    }

    /**
     * Create an instance of {@link PaymentType }
     * 
     */
    public PaymentType createPaymentType() {
        return new PaymentType();
    }

    /**
     * Create an instance of {@link ProductContactNumberList }
     * 
     */
    public ProductContactNumberList createProductContactNumberList() {
        return new ProductContactNumberList();
    }

    /**
     * Create an instance of {@link ServiceDetail }
     * 
     */
    public ServiceDetail createServiceDetail() {
        return new ServiceDetail();
    }

    /**
     * Create an instance of {@link ZoneList }
     * 
     */
    public ZoneList createZoneList() {
        return new ZoneList();
    }

    /**
     * Create an instance of {@link ConfirmationServiceDataInsurance }
     * 
     */
    public ConfirmationServiceDataInsurance createConfirmationServiceDataInsurance() {
        return new ConfirmationServiceDataInsurance();
    }

    /**
     * Create an instance of {@link ContactData }
     * 
     */
    public ContactData createContactData() {
        return new ContactData();
    }

    /**
     * Create an instance of {@link ServicePrice }
     * 
     */
    public ServicePrice createServicePrice() {
        return new ServicePrice();
    }

    /**
     * Create an instance of {@link ServiceInsurance }
     * 
     */
    public ServiceInsurance createServiceInsurance() {
        return new ServiceInsurance();
    }

    /**
     * Create an instance of {@link ProductHotelIssueList }
     * 
     */
    public ProductHotelIssueList createProductHotelIssueList() {
        return new ProductHotelIssueList();
    }

    /**
     * Create an instance of {@link ServiceCarPreferenceList }
     * 
     */
    public ServiceCarPreferenceList createServiceCarPreferenceList() {
        return new ServiceCarPreferenceList();
    }

    /**
     * Create an instance of {@link ServiceDetailList }
     * 
     */
    public ServiceDetailList createServiceDetailList() {
        return new ServiceDetailList();
    }

    /**
     * Create an instance of {@link ProductFeatureDistanceItemList }
     * 
     */
    public ProductFeatureDistanceItemList createProductFeatureDistanceItemList() {
        return new ProductFeatureDistanceItemList();
    }

    /**
     * Create an instance of {@link ServiceTransfer }
     * 
     */
    public ServiceTransfer createServiceTransfer() {
        return new ServiceTransfer();
    }

    /**
     * Create an instance of {@link ServiceTicketModality }
     * 
     */
    public ServiceTicketModality createServiceTicketModality() {
        return new ServiceTicketModality();
    }

    /**
     * Create an instance of {@link ProductHotelCategoryGroupList }
     * 
     */
    public ProductHotelCategoryGroupList createProductHotelCategoryGroupList() {
        return new ProductHotelCategoryGroupList();
    }

    /**
     * Create an instance of {@link ServiceInsuranceCoverage }
     * 
     */
    public ServiceInsuranceCoverage createServiceInsuranceCoverage() {
        return new ServiceInsuranceCoverage();
    }

    /**
     * Create an instance of {@link Price }
     * 
     */
    public Price createPrice() {
        return new Price();
    }

    /**
     * Create an instance of {@link OperationDateList }
     * 
     */
    public OperationDateList createOperationDateList() {
        return new OperationDateList();
    }

    /**
     * Create an instance of {@link ProductTransfer }
     * 
     */
    public ProductTransfer createProductTransfer() {
        return new ProductTransfer();
    }

    /**
     * Create an instance of {@link Purchase }
     * 
     */
    public Purchase createPurchase() {
        return new Purchase();
    }

    /**
     * Create an instance of {@link ContractClassification }
     * 
     */
    public ContractClassification createContractClassification() {
        return new ContractClassification();
    }

    /**
     * Create an instance of {@link DestinationList }
     * 
     */
    public DestinationList createDestinationList() {
        return new DestinationList();
    }

    /**
     * Create an instance of {@link HotelValuedAvailRQ }
     * 
     */
    public HotelValuedAvailRQ createHotelValuedAvailRQ() {
        return new HotelValuedAvailRQ();
    }

    /**
     * Create an instance of {@link Customer }
     * 
     */
    public Customer createCustomer() {
        return new Customer();
    }

    /**
     * Create an instance of {@link ProductHotelBoard }
     * 
     */
    public ProductHotelBoard createProductHotelBoard() {
        return new ProductHotelBoard();
    }

    /**
     * Create an instance of {@link ProductCar }
     * 
     */
    public ProductCar createProductCar() {
        return new ProductCar();
    }

}
