//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.18 at 11:06:15 AM CET 
//


package com.photel.hotelan.client.IrqZoneList;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.photel.hotelan.client.IrqZoneList package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class IrqZoneListObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.photel.hotelan.client.IrqZoneList
     * 
     */
    public IrqZoneListObjectFactory() {
    }

    /**
     * Create an instance of {@link IrqZoneListResponse }
     * 
     */
    public IrqZoneListResponse createResponse() {
        return new IrqZoneListResponse();
    }


    /**
     * Create an instance of {@link Zones }
     * 
     */
    public Zones createZones() {
        return new Zones();
    }

    /**
     * Create an instance of {@link Zone }
     * 
     */
    public Zone createZone() {
        return new Zone();
    }

}
