//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.18 at 11:04:52 AM CET 
//


package com.photel.hotelan.client.IrqHotelNonAvailability;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.photel.hotelan.client.IrqHotelNonAvailability package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class IrqHotelNonAvailabilityObjectFactory {

    private final static QName _Error_QNAME = new QName("", "Error");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.photel.hotelan.client.IrqHotelNonAvailability
     * 
     */
    public IrqHotelNonAvailabilityObjectFactory() {
    }

    /**
     * Create an instance of {@link IrqHotelNonAvailabilityResponse }
     * 
     */
    public IrqHotelNonAvailabilityResponse createResponse() {
        return new IrqHotelNonAvailabilityResponse();
    }

    /**
     * Create an instance of {@link NonAvailability }
     * 
     */
    public NonAvailability createNonAvailability() {
        return new NonAvailability();
    }

    /**
     * Create an instance of {@link Hotel }
     * 
     */
    public Hotel createHotel() {
        return new Hotel();
    }

    /**
     * Create an instance of {@link RoomType }
     * 
     */
    public RoomType createRoomType() {
        return new RoomType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Error")
    public JAXBElement<String> createError(String value) {
        return new JAXBElement<String>(_Error_QNAME, String.class, null, value);
    }

}
