//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.18 at 04:31:11 PM CET 
//


package com.photel.hotelan.client.IrqVillaConfirmReservation;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.photel.hotelan.client.IrqVillaConfirmReservation package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class IrqVillaConfirmReservationObjectFactory {

    private final static QName _HotelId_QNAME = new QName("", "HotelId");
    private final static QName _RoomId_QNAME = new QName("", "RoomId");
    private final static QName _BoardId_QNAME = new QName("", "BoardId");
    private final static QName _Price_QNAME = new QName("", "Price");
    private final static QName _Error_QNAME = new QName("", "Error");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.photel.hotelan.client.IrqVillaConfirmReservation
     * 
     */
    public IrqVillaConfirmReservationObjectFactory() {
    }

    /**
     * Create an instance of {@link Reserve }
     * 
     */
    public Reserve createReserve() {
        return new Reserve();
    }

    /**
     * Create an instance of {@link IrqVillaConfirmReservationResponse }
     * 
     */
    public IrqVillaConfirmReservationResponse createResponse() {
        return new IrqVillaConfirmReservationResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HotelId")
    public JAXBElement<String> createHotelId(String value) {
        return new JAXBElement<String>(_HotelId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RoomId")
    public JAXBElement<String> createRoomId(String value) {
        return new JAXBElement<String>(_RoomId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BoardId")
    public JAXBElement<String> createBoardId(String value) {
        return new JAXBElement<String>(_BoardId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Price")
    public JAXBElement<String> createPrice(String value) {
        return new JAXBElement<String>(_Price_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Error")
    public JAXBElement<String> createError(String value) {
        return new JAXBElement<String>(_Error_QNAME, String.class, null, value);
    }

}
