//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.11 at 11:27:53 AM CEST 
//


package com.photel.webserviceClient.BDL244.vo.cancel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Contains simple zone list for a zone group.
 * 
 * <p>Java class for ZoneGroup complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ZoneGroup">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GroupZone" type="{http://www.hotelbeds.com/schemas/2005/06/messages}Zone"/>
 *         &lt;element name="SimpleZoneList" type="{http://www.hotelbeds.com/schemas/2005/06/messages}ZoneList"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ZoneGroup", propOrder = {
    "groupZone",
    "simpleZoneList"
})
public class ZoneGroup {

    @XmlElement(name = "GroupZone", required = true)
    protected Zone groupZone;
    @XmlElement(name = "SimpleZoneList", required = true)
    protected ZoneList simpleZoneList;

    /**
     * Gets the value of the groupZone property.
     * 
     * @return
     *     possible object is
     *     {@link Zone }
     *     
     */
    public Zone getGroupZone() {
        return groupZone;
    }

    /**
     * Sets the value of the groupZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link Zone }
     *     
     */
    public void setGroupZone(Zone value) {
        this.groupZone = value;
    }

    /**
     * Gets the value of the simpleZoneList property.
     * 
     * @return
     *     possible object is
     *     {@link ZoneList }
     *     
     */
    public ZoneList getSimpleZoneList() {
        return simpleZoneList;
    }

    /**
     * Sets the value of the simpleZoneList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZoneList }
     *     
     */
    public void setSimpleZoneList(ZoneList value) {
        this.simpleZoneList = value;
    }

}
